[package]
name = "gpui-dot"
version = "0.1.0"
edition = "2024"
description = "dotv — a DOT graph visualizer built with GPUI and GPUI Kit"

[[bin]]
name = "dotv"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
gpui-kit = "0.6.6"
rust-embed = { version = "8", features = ["debug-embed"] }
tikv-jemallocator = { version = "0.7.0", features = [
    "unprefixed_malloc_on_supported_platforms",
] }

[dev-dependencies]
gpui-kit = { version = "0.6.6", features = ["test-support"] }


[profile.release]
debug = false
strip = "none"
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
