//! The GUI's view of a dot layout: `dotgen`'s output (points, y up) converted
//! into world-space render data (y down), with colors/styles resolved from the
//! DOT attributes, arrowheads generated by [`crate::dotgen::arrows`], and the
//! drag-time re-routing used while a node is moved off its laid-out spot.

use std::borrow::Cow;
use std::collections::BTreeMap;

use gpui_kit::{Hsla, SharedString};

use crate::dotgen::{self, DotLayout, EdgeOut, LabelOut, NodeOut};
use crate::graph::model::Graph;
use crate::viz::layout::RankDir;

/// A label ready to paint (world coordinates, y down).
#[derive(Debug, Clone)]
pub struct ViewLabel {
    /// Text with `\N`-style escapes resolved; lines separated by `\n`.
    pub text: String,
    /// Per-line justification (`'l'`, `'r'` or `'n'`), one entry per line.
    pub just: Vec<char>,
    /// Center of the text block.
    pub center: (f32, f32),
    /// Width of the label's box (`dimen.x`, the widest line) — the reference
    /// a left/right-justified line aligns against.
    pub space: f32,
    pub font_size: f32,
    pub color: Option<Hsla>,
}

/// How to draw a node's outline. The variants mirror dot's shape families so
/// the painter can pick the right GPU path: rectangles go through quads,
/// ellipses through the true ellipse sampler, and everything else stays a
/// polygon with sharp edges.
#[derive(Debug, Clone)]
pub enum NodeShape {
    /// Axis-aligned rectangles, one `(x, y, w, h)` per periphery ring, world
    /// coordinates — `box`/`rect`/`rectangle`, records. Painted directly as
    /// rounded-rect quads (fill + border in one `paint_quad`).
    Rect(Vec<(f32, f32, f32, f32)>),
    /// Closed polygons (one per periphery ring), world coordinates. Rendered
    /// exactly: every corner stays sharp.
    Polygons(Vec<Vec<(f32, f32)>>),
    /// Axis-aligned ellipses centered on the node box, one `(half_width,
    /// half_height)` per periphery ring, innermost first (doublecircle &co).
    /// A circle is the `rx == ry` case and paints through a quad.
    Ellipse(Vec<(f32, f32)>),
    /// No outline (`plaintext`/`none`): only the label is drawn.
    None,
}

/// One arrowhead piece in world coordinates.
#[derive(Debug, Clone)]
pub enum ArrowPart {
    Polygon(Vec<(f32, f32)>, bool),
    Polyline(Vec<(f32, f32)>),
    Ellipse((f32, f32), (f32, f32), bool),
    Bezier([(f32, f32); 4]),
}

/// A node placed by dot, ready to paint and hit-test.
#[derive(Debug, Clone)]
pub struct ViewNode {
    /// Box top-left and size, world coordinates (y down).
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
    pub shape: NodeShape,
    pub fill: Option<Hsla>,
    pub stroke: Hsla,
    pub penwidth: f32,
    pub dashed: bool,
    pub dotted: bool,
    pub rounded: bool,
    pub peripheries: usize,
    pub label: Option<ViewLabel>,
    /// `shape=record`: the painted fields and dividers, world coordinates.
    /// When present the node's outline is a rectangle and the label is drawn
    /// per field instead of once, centred.
    pub record: Option<ViewRecord>,
}

/// A record node's painted structure, in world coordinates (y down).
#[derive(Debug, Clone, Default)]
pub struct ViewRecord {
    /// `(x, y, w, h, text)` per leaf field.
    pub fields: Vec<(f32, f32, f32, f32, SharedString)>,
    /// Divider segments between sibling fields.
    pub dividers: Vec<((f32, f32), (f32, f32))>,
}

/// An edge routed by dot.
#[derive(Debug, Clone)]
pub struct ViewEdge {
    pub tail: usize,
    pub head: usize,
    /// Cubic segments sharing endpoints, world coordinates.
    pub segments: Vec<[(f32, f32); 4]>,
    pub arrows: Vec<ArrowPart>,
    pub label: Option<ViewLabel>,
    pub color: Hsla,
    /// The `color` attribute as a colorList (`"red:blue"`); each Bézier
    /// segment is painted with the next entry (cycling), arrows with the
    /// last — emit.c's behavior. Single-entry for a plain color.
    pub colors: Vec<Hsla>,
    pub penwidth: f32,
    pub dashed: bool,
    pub dotted: bool,
    /// Arrow flags + anchors kept for drag-time re-arrowing.
    pub sflag: u32,
    pub eflag: u32,
    /// The true arrow-tip anchors dot recorded (`bezier.sp`/`.ep`, on the node
    /// border), when the corresponding flag is set; the spline end is the
    /// arrow's *base* a little short of it.
    pub stip: (f32, f32),
    pub etip: (f32, f32),
    arrowsize: f64,
}

impl ViewEdge {
    /// The spline pull-back the arrowhead at `flag` needs (`arrow_length`).
    pub fn arrow_len(&self, flag: u32) -> f64 {
        dotgen::arrows::arrow_pull_len(flag, self.arrowsize, self.penwidth as f64)
    }

    /// The arrow tip anchor on the node border: the head end when `head`,
    /// else the tail end.
    fn tip(&self, head: bool) -> (f32, f32) {
        if head { self.etip } else { self.stip }
    }
}

/// A cluster box.
#[derive(Debug, Clone)]
pub struct ViewCluster {
    pub rect: (f32, f32, f32, f32),
    pub label: Option<ViewLabel>,
    pub stroke: Hsla,
    pub fill: Option<Hsla>,
    pub dashed: bool,
}

/// The whole laid-out graph in render form.
#[derive(Debug, Clone, Default)]
pub struct DotView {
    pub nodes: Vec<ViewNode>,
    pub edges: Vec<ViewEdge>,
    pub clusters: Vec<ViewCluster>,
    /// `(min_x, min_y, max_x, max_y)` covering the drawing.
    pub bounds: (f32, f32, f32, f32),
    pub rank_dir: RankDir,
}

impl DotView {
    /// Builds the view from a dot layout plus the source graph (attributes)
    /// and per-label text extents.
    pub fn build(layout: &DotLayout, graph: &Graph, rank_dir: RankDir) -> Self {
        let bb = layout.bb;
        let map = |p: dotgen::geom::PointF| {
            ((p.x - bb.ll.x) as f32, (bb.ur.y - p.y) as f32)
        };

        let nodes: Vec<ViewNode> = layout
            .nodes
            .iter()
            .map(|n| view_node(n, graph, map))
            .collect();
        let edges: Vec<ViewEdge> = layout
            .edges
            .iter()
            .map(|e| view_edge(e, graph, map))
            .collect();
        let clusters: Vec<ViewCluster> = layout
            .clusters
            .iter()
            .map(|c| {
                let ll = map(c.bb.ll);
                let ur = map(c.bb.ur);
                let attrs = graph
                    .subgraphs
                    .iter()
                    .find(|s| s.name == c.name)
                    .map(|s| &s.attrs);
                let style = Style::parse(attrs.and_then(|a| a.get("style")).map(String::as_str));
                ViewCluster {
                    rect: (ll.0, ur.1, (ur.0 - ll.0).abs(), (ll.1 - ur.1).abs()),
                    label: c.label.as_ref().map(|l| view_label(l, map, attrs, None)),
                    stroke: color_of(attrs.and_then(|a| a.get("color")))
                        .unwrap_or_else(|| Hsla::from(gpui_kit::rgb(0x888888))),
                    fill: style
                        .filled
                        .then(|| color_of(attrs.and_then(|a| a.get("fillcolor"))))
                        .flatten()
                        // graphviz: a filled cluster defaults to its `color`,
                        // else lightgrey
                        .or_else(|| color_of(attrs.and_then(|a| a.get("color"))))
                        .or_else(|| Some(Hsla::from(gpui_kit::rgb(0xd3d3d3)))),
                    dashed: style.dashed,
                }
            })
            .collect();

        // bounds: the dot bounding box maps to (0,0)-(w,h); widen by any node
        // ink that sticks out (penwidth) so nothing is clipped.
        let mut bounds: (f32, f32, f32, f32) = (
            0.0,
            0.0,
            (bb.ur.x - bb.ll.x) as f32,
            (bb.ur.y - bb.ll.y) as f32,
        );
        for n in &nodes {
            bounds.0 = bounds.0.min(n.x);
            bounds.1 = bounds.1.min(n.y);
            bounds.2 = bounds.2.max(n.x + n.w);
            bounds.3 = bounds.3.max(n.y + n.h);
        }
        Self {
            nodes,
            edges,
            clusters,
            bounds,
            rank_dir,
        }
    }

    /// Node boxes with committed drag offsets applied.
    pub fn boxes_with_offsets(&self, offsets: &[(f32, f32)]) -> Vec<(f32, f32, f32, f32)> {
        self.nodes
            .iter()
            .enumerate()
            .map(|(i, n)| {
                let (dx, dy) = offsets.get(i).copied().unwrap_or((0.0, 0.0));
                (n.x + dx, n.y + dy, n.w, n.h)
            })
            .collect()
    }

    /// The edges as painted for this frame: each edge is either its routed
    /// self, or — when one of its endpoints is being dragged — re-routed from
    /// the moved node's border to the fixed far end (arrows rebuilt).
    ///
    /// Borrows the routed edges whenever no node is moved (the common case),
    /// so painting never deep-clones every edge's segments, arrows and labels
    /// per frame; the owned clone is paid only while a drag is live.
    pub fn edges_with_offsets(&self, offsets: &[(f32, f32)]) -> Cow<'_, [ViewEdge]> {
        if offsets.iter().all(|&(dx, dy)| dx == 0.0 && dy == 0.0) {
            return Cow::Borrowed(&self.edges);
        }
        Cow::Owned(
        self.edges
            .iter()
            .map(|e| {
                let tail_moved = offsets.get(e.tail).copied().unwrap_or((0.0, 0.0));
                let head_moved = offsets.get(e.head).copied().unwrap_or((0.0, 0.0));
                if tail_moved == (0.0, 0.0) && head_moved == (0.0, 0.0) {
                    return e.clone();
                }
                let mut moved = e.clone();
                let node = |i: usize| -> (f32, f32, f32, f32) {
                    let n = &self.nodes[i];
                    let (dx, dy) = offsets.get(i).copied().unwrap_or((0.0, 0.0));
                    (n.x + dx, n.y + dy, n.w, n.h)
                };
                // dot's end geometry: the arrow *tip* sits on the node border
                // and the spline stops at the arrow's *base*, pulled back
                // along the approach direction (arrow_clip). Both the tip and
                // the pulled-back endpoint move with the dragged node, so the
                // arrowhead follows the node and the line never pokes out
                // past it.
                let mut tail_tip = None;
                let mut head_tip = None;
                if tail_moved != (0.0, 0.0) {
                    let from = border_point(node(e.tail), far_end(e, false));
                    if let Some(first) = moved.segments.first_mut() {
                        first[1] = lerp(from, first[3], 1.0 / 3.0);
                        first[0] = pull_back(from, first[1], e.arrow_len(e.sflag));
                    }
                    tail_tip = Some(from);
                }
                if head_moved != (0.0, 0.0) {
                    let to = border_point(node(e.head), far_end(e, true));
                    if let Some(last) = moved.segments.last_mut() {
                        last[2] = lerp(last[0], to, 2.0 / 3.0);
                        last[3] = pull_back(to, last[2], e.arrow_len(e.eflag));
                    }
                    head_tip = Some(to);
                }
                let tail_tip = tail_tip.unwrap_or_else(|| {
                    if e.sflag != 0 { e.tip(false) } else { moved.segments.first().map(|s| s[0]).unwrap_or((0.0, 0.0)) }
                });
                let head_tip = head_tip.unwrap_or_else(|| {
                    if e.eflag != 0 { e.tip(true) } else { moved.segments.last().map(|s| s[3]).unwrap_or((0.0, 0.0)) }
                });
                moved.arrows = build_arrow_parts(
                    &moved.segments,
                    e.sflag,
                    e.eflag,
                    e.arrowsize,
                    tail_tip,
                    head_tip,
                );
                // The label follows the re-routed spline: dot centers edge
                // labels on the spline's midpoint, and that midpoint moves by
                // the mean of the endpoint offsets (the full offset when both
                // ends move together).
                if let Some(label) = moved.label.as_mut() {
                    label.center.0 += (tail_moved.0 + head_moved.0) / 2.0;
                    label.center.1 += (tail_moved.1 + head_moved.1) / 2.0;
                }
                moved
            })
            .collect())
    }
}

fn far_end(e: &ViewEdge, tail_side: bool) -> (f32, f32) {
    if tail_side {
        e.segments
            .last()
            .map(|s| s[3])
            .unwrap_or((0.0, 0.0))
    } else {
        e.segments.first().map(|s| s[0]).unwrap_or((0.0, 0.0))
    }
}

fn lerp(a: (f32, f32), b: (f32, f32), t: f32) -> (f32, f32) {
    (a.0 + (b.0 - a.0) * t, a.1 + (b.1 - a.1) * t)
}

/// The point on the ray `tip → toward` set back from `tip` by `len` world
/// units — where the spline must stop so the arrowhead covers the gap
/// (`arrow_clip`'s pull-back, approximated along the approach direction).
/// Clamped at `toward` so a short segment can't invert.
fn pull_back(tip: (f32, f32), toward: (f32, f32), len: f64) -> (f32, f32) {
    let len = len as f32;
    if len <= 0.0 {
        return tip;
    }
    let (dx, dy) = sub(toward, tip);
    let d = (dx * dx + dy * dy).sqrt();
    if d < 1e-6 {
        return tip;
    }
    let t = (len / d).min(1.0);
    (tip.0 + dx * t, tip.1 + dy * t)
}

/// The point where the segment from the node's centre toward `toward` leaves
/// its border (ellipse or box approximation, matching the node's shape).
fn border_point(rect: (f32, f32, f32, f32), toward: (f32, f32)) -> (f32, f32) {
    let (x, y, w, h) = rect;
    let cx = x + w / 2.0;
    let cy = y + h / 2.0;
    let dx = toward.0 - cx;
    let dy = toward.1 - cy;
    if dx.abs() < 1e-6 && dy.abs() < 1e-6 {
        return (cx, cy);
    }
    // scale the ray so it meets the box edge
    let sx = if dx.abs() > 1e-6 {
        (w / 2.0) / dx.abs()
    } else {
        f32::INFINITY
    };
    let sy = if dy.abs() > 1e-6 {
        (h / 2.0) / dy.abs()
    } else {
        f32::INFINITY
    };
    let s = sx.min(sy);
    (cx + dx * s, cy + dy * s)
}

fn view_node(
    n: &NodeOut,
    graph: &Graph,
    map: impl Fn(dotgen::geom::PointF) -> (f32, f32),
) -> ViewNode {
    let attrs = &graph.nodes[n.input].attrs;
    let style = Style::parse(attrs.get("style").map(String::as_str));
    let w = (n.lw + n.rw) as f32;
    let h = n.ht as f32;
    let center = map(n.coord);
    let (x, y) = (center.0 - w / 2.0, center.1 - h / 2.0);

    let shape_name = if n.shape.kind.is_empty() {
        attrs
            .get("shape")
            .map(String::as_str)
            .unwrap_or("ellipse")
            .to_string()
    } else {
        n.shape.kind.clone()
    };
    // Records draw as a rectangle with internal dividers and per-field text.
    let record = n.record.as_ref().map(|r| {
        // `record_parts` is node-relative; lift it onto the node's centre.
        let at = |p: dotgen::geom::PointF| map(dotgen::geom::PointF::new(
            n.coord.x + p.x,
            n.coord.y + p.y,
        ));
        let fields = r
            .fields
            .iter()
            .map(|f| {
                let ll = at(f.ll);
                let ur = at(f.ur);
                (
                    ll.0.min(ur.0),
                    ll.1.min(ur.1),
                    (ur.0 - ll.0).abs(),
                    (ur.1 - ll.1).abs(),
                    SharedString::from(f.text.clone()),
                )
            })
            .collect();
        let dividers = r
            .dividers
            .iter()
            .map(|(a, b)| (at(*a), at(*b)))
            .collect();
        ViewRecord { fields, dividers }
    });
    let shape_name = if record.is_some() && shape_name == "Mrecord" {
        "box".to_string()
    } else {
        shape_name
    };
    // The descriptor the node actually resolved: poly_init layered the user's
    // `sides`/`skew`/`distortion`/`orientation`/`regular`/`peripheries` onto
    // the table defaults. `shape=polygon` has table `sides` 0, so painting
    // from the bare table entry would turn every user polygon into a box or
    // an ellipse.
    let desc = dotgen::shapes::resolved_desc(
        &dotgen::shapes::shape_of(&shape_name),
        &n.shape,
    );
    let shape = if record.is_some() && !style.invisible {
        // the record outline is its bounding rectangle
        NodeShape::Rect(vec![(x, y, w, h)])
    } else if style.invisible {
        NodeShape::None
    } else if shape_name == "plaintext" || shape_name == "plain" || shape_name == "none" {
        NodeShape::None
    } else if n.shape.sides <= 2 && shape_name != "point" && !n.shape.kind.is_empty() {
        // computed ellipse family (ellipse/circle/doublecircle/…; skewed or
        // distorted `sides <= 2` polygons resolve to `sides = 120` instead)
        NodeShape::Ellipse(ellipse_rings_world(&desc, n))
    } else if shape_name == "circle" || shape_name == "ellipse" || shape_name == "oval" {
        NodeShape::Ellipse(ellipse_rings_world(&desc, n))
    } else {
        // Plain rings first: `style=rounded` would replace a box's four
        // corners with arc samples, and the rect check needs the raw corners.
        let polygons = dotgen::shapes::shape_vertices(
            &desc,
            n.lw,
            n.rw,
            n.ht,
            n.penwidth,
            false,
        );
        if polygons.is_empty() {
            NodeShape::Ellipse(ellipse_rings_world(&desc, n))
        } else if let Some(rects) = rect_rings(&polygons) {
            // box / rect / rectangle (peripheries included): paint as quads.
            // `shape_vertices` rings are node-relative (y up); lift them onto
            // the node's centre and through the world map like the polygon
            // rings below.
            NodeShape::Rect(
                rects
                    .into_iter()
                    .map(|(x, y, w, h)| {
                        let a = map(dotgen::geom::PointF::new(
                            n.coord.x + x as f64,
                            n.coord.y + y as f64,
                        ));
                        let b = map(dotgen::geom::PointF::new(
                            n.coord.x + (x + w) as f64,
                            n.coord.y + (y + h) as f64,
                        ));
                        (a.0.min(b.0), a.1.min(b.1), (b.0 - a.0).abs(), (b.1 - a.1).abs())
                    })
                    .collect(),
            )
        } else {
            let rings = if style.rounded && !desc.poly.diagonals && desc.poly.shape_code == 0 {
                dotgen::shapes::shape_vertices(&desc, n.lw, n.rw, n.ht, n.penwidth, true)
            } else {
                polygons.clone()
            };
            NodeShape::Polygons(
                rings
                    .into_iter()
                    .map(|ring| {
                        ring.into_iter()
                            .map(|p| map(dotgen::geom::PointF::new(n.coord.x + p.x, n.coord.y + p.y)))
                            .collect()
                    })
                    .collect(),
            )
        }
    };

    let stroke = color_of(attrs.get("color")).unwrap_or(Hsla::from(gpui_kit::rgb(0x1f2937)));
    let fill = if style.filled {
        color_of(attrs.get("fillcolor"))
            .or_else(|| color_of(attrs.get("color")))
            .or_else(|| Some(Hsla::from(gpui_kit::rgb(0xd3d3d3))))
    } else {
        None
    };
    // Label color: `fontcolor`, else — graphviz paints filled-shape labels
    // black (the default `fontcolor`) — black over a fill, else the theme's
    // foreground keeps unfilled nodes readable on the dark canvas.
    let label_fallback = fill.map(|_| Hsla::from(gpui_kit::rgb(0x111111)));
    ViewNode {
        x,
        y,
        w,
        h,
        shape,
        fill,
        stroke,
        penwidth: n.penwidth as f32,
        dashed: style.dashed,
        dotted: style.dotted,
        rounded: style.rounded,
        peripheries: n.shape.peripheries.max(1) as usize,
        label: n
            .label
            .as_ref()
            .map(|l| view_label(l, &map, Some(attrs), label_fallback)),
        record,
    }
}

/// Drawable periphery half-extents for an ellipse-family node: the rings
/// `ellipse_rings` returns, minus the penwidth/2 spline-clip ring.
fn ellipse_rings_world(
    desc: &dotgen::shapes::ShapeDesc,
    n: &NodeOut,
) -> Vec<(f32, f32)> {
    let rings = dotgen::shapes::ellipse_rings(desc, n.lw, n.rw, n.ht, n.penwidth);
    let drawn = rings.len().min(n.shape.peripheries.max(1) as usize);
    rings[..drawn]
        .iter()
        .map(|&(hx, hy)| (hx as f32, hy as f32))
        .collect()
}

/// The bounding rect of each ring when *every* ring is an axis-aligned
/// four-corner rectangle (box / rect / rectangle, records) — `None` when any
/// ring deviates (diamond, pentagon, skewed box, …), which must stay a
/// polygon.
fn rect_rings(rings: &[Vec<dotgen::geom::PointF>]) -> Option<Vec<(f32, f32, f32, f32)>> {
    rings
        .iter()
        .map(|ring| {
            let mut unique: Vec<(f32, f32)> = Vec::with_capacity(4);
            for p in ring {
                let (x, y) = (p.x as f32, p.y as f32);
                if !unique.iter().any(|&(ux, uy)| (ux - x).abs() < 1e-4 && (uy - y).abs() < 1e-4) {
                    unique.push((x, y));
                }
            }
            if unique.len() != 4 {
                return None;
            }
            let (mut min_x, mut min_y) = (f32::INFINITY, f32::INFINITY);
            let (mut max_x, mut max_y) = (f32::NEG_INFINITY, f32::NEG_INFINITY);
            for &(x, y) in &unique {
                min_x = min_x.min(x);
                min_y = min_y.min(y);
                max_x = max_x.max(x);
                max_y = max_y.max(y);
            }
            if max_x - min_x <= 1e-3 || max_y - min_y <= 1e-3 {
                return None; // degenerate
            }
            const EPS: f32 = 1e-3;
            let corners = [
                (min_x, min_y),
                (max_x, min_y),
                (max_x, max_y),
                (min_x, max_y),
            ];
            if unique.iter().any(|&(x, y)| {
                !corners
                    .iter()
                    .any(|&(cx, cy)| (x - cx).abs() <= EPS && (y - cy).abs() <= EPS)
            }) {
                return None;
            }
            Some((min_x, min_y, max_x - min_x, max_y - min_y))
        })
        .collect()
}

fn view_edge(
    e: &EdgeOut,
    graph: &Graph,
    map: impl Fn(dotgen::geom::PointF) -> (f32, f32),
) -> ViewEdge {
    let attrs = &graph.edges[e.input].attrs;
    let style = Style::parse(attrs.get("style").map(String::as_str));
    let colors: Vec<Hsla> = attrs
        .get("color")
        .map(|value| {
            value
                .split(':')
                .filter_map(|part| color_of_str(Some(part)))
                .collect::<Vec<_>>()
        })
        .filter(|colors| !colors.is_empty())
        .unwrap_or_else(|| vec![Hsla::from(gpui_kit::rgb(0x4b5563))]);
    let color = colors[0];
    let segments: Vec<[(f32, f32); 4]> = e
        .segments
        .iter()
        .map(|s| {
            [
                map(s[0]),
                map(s[1]),
                map(s[2]),
                map(s[3]),
            ]
        })
        .collect();
    let arrowsize = late_double(attrs.get("arrowsize"), 1.0);
    // dot records the true tip anchors in the Bézier (`bezier.sp`/`.ep`); the
    // routed points end at the arrow's *base*, so the head must be placed at
    // `ep` (and the tail at `sp`) or the arrowhead lands inside the channel.
    let tail_tip = if e.sflag != 0 { map(e.sp) } else { segments.first().map(|s| s[0]).unwrap_or((0.0, 0.0)) };
    let head_tip = if e.eflag != 0 { map(e.ep) } else { segments.last().map(|s| s[3]).unwrap_or((0.0, 0.0)) };
    let (stip, etip) = (tail_tip, head_tip);
    let arrows = build_arrow_parts(
        &segments,
        e.sflag,
        e.eflag,
        arrowsize,
        tail_tip,
        head_tip,
    );
    ViewEdge {
        tail: e.tail,
        head: e.head,
        segments,
        arrows,
        stip,
        etip,
        // dot paints edge labels with `fontcolor`, defaulting to black — not
        // with the edge's own color, so no fallback is passed here.
        label: e
            .label
            .as_ref()
            .map(|l| view_label(l, &map, Some(attrs), None)),
        color,
        colors,
        penwidth: e.penwidth as f32,
        dashed: style.dashed,
        dotted: style.dotted,
        sflag: e.sflag,
        eflag: e.eflag,
        arrowsize,
    }
}

/// Regenerates the arrowhead pieces for the given routed segments.
fn build_arrow_parts(
    segments: &[[(f32, f32); 4]],
    sflag: u32,
    eflag: u32,
    arrowsize: f64,
    tail_tip: (f32, f32),
    head_tip: (f32, f32),
) -> Vec<ArrowPart> {
    let mut out = Vec::new();
    if segments.is_empty() {
        return out;
    }
    let first = segments[0];
    let last = *segments.last().unwrap();
    if eflag != 0 {
        // emit.c: `arrow_gen(..., bz.ep, bz.list[size-1], ...)`; arrow_gen then
        // forms `u = list[size-1] - ep`, i.e. the vector pointing *back* along
        // the edge — the triangle's apex sits at ep, its base behind it.
        let dir = sub(last[2], head_tip);
        out.extend(arrow_parts(head_tip, dir, arrowsize, eflag));
    }
    if sflag != 0 {
        // emit.c: `arrow_gen(..., bz.sp, bz.list[0], ...)` → u = list[0] - sp
        // (pointing forward along the edge), so the apex lands on sp.
        let dir = sub(first[1], tail_tip);
        out.extend(arrow_parts(tail_tip, dir, arrowsize, sflag));
    }
    out
}

/// Runs the ported `arrow_gen` for one end and converts its pieces to world
/// coordinates (a pure y-flip: polygon winding does not matter for fills).
fn arrow_parts(tip: (f32, f32), dir: (f32, f32), arrowsize: f64, flag: u32) -> Vec<ArrowPart> {
    let (dx, dy) = if dir.0.abs() < 1e-6 && dir.1.abs() < 1e-6 {
        (0.0, 1.0)
    } else {
        dir
    };
    // `arrow_gen(p, u_ref)`: u = u_ref - p, so pass the tip plus the direction.
    let p = dotgen::geom::PointF::new(tip.0 as f64, -(tip.1 as f64));
    let u_ref = dotgen::geom::PointF::new((tip.0 + dx) as f64, -((tip.1 + dy) as f64));
    let out = dotgen::arrows::arrow_gen(p, u_ref, arrowsize, 1.0, flag);
    let flip = |q: dotgen::geom::PointF| -> (f32, f32) { (q.x as f32, -(q.y as f32)) };
    out.shapes
        .into_iter()
        .map(|s| match s {
            dotgen::arrows::ArrowShape::Polygon(pts, filled) => {
                ArrowPart::Polygon(pts.into_iter().map(flip).collect(), filled)
            }
            dotgen::arrows::ArrowShape::Polyline(pts) => {
                ArrowPart::Polyline(pts.into_iter().map(flip).collect())
            }
            dotgen::arrows::ArrowShape::Ellipse(a, b, filled) => {
                ArrowPart::Ellipse(flip(a), flip(b), filled)
            }
            dotgen::arrows::ArrowShape::Bezier(b) => {
                ArrowPart::Bezier([flip(b[0]), flip(b[1]), flip(b[2]), flip(b[3])])
            }
        })
        .collect()
}

fn sub(a: (f32, f32), b: (f32, f32)) -> (f32, f32) {
    (a.0 - b.0, a.1 - b.1)
}

fn view_label(
    l: &LabelOut,
    map: impl Fn(dotgen::geom::PointF) -> (f32, f32),
    attrs: Option<&BTreeMap<String, String>>,
    fallback: Option<Hsla>,
) -> ViewLabel {
    let center = map(l.pos);
    let color = attrs
        .and_then(|a| color_of(a.get("fontcolor")))
        .or(fallback);
    ViewLabel {
        text: l.text.clone(),
        just: l.just.clone(),
        space: l.dimen.x as f32,
        center,
        font_size: l.fontsize as f32,
        color,
    }
}

/// The parsed `style` attribute.
#[derive(Debug, Clone, Copy, Default)]
struct Style {
    filled: bool,
    rounded: bool,
    dashed: bool,
    dotted: bool,
    invisible: bool,
}

impl Style {
    fn parse(value: Option<&str>) -> Self {
        let mut s = Style::default();
        if let Some(value) = value {
            for part in value.split(',') {
                match part.trim() {
                    "filled" => s.filled = true,
                    "rounded" => s.rounded = true,
                    "dashed" => s.dashed = true,
                    "dotted" => s.dotted = true,
                    "invis" | "invisible" => s.invisible = true,
                    _ => {}
                }
            }
        }
        s
    }
}

fn late_double(value: Option<&String>, def: f64) -> f64 {
    value
        .and_then(|s| s.trim().parse::<f64>().ok())
        .unwrap_or(def)
}

/// DOT color parsing: `#rrggbb`, `#rrggbbaa`, `H,S,V` floats, or a name from
/// the X11 set graphviz ships. `"none"` and the empty string mean "unset".
pub fn color_of(value: Option<&String>) -> Option<Hsla> {
    color_of_str(value.map(String::as_str))
}

/// [`color_of`] over a plain `&str`.
pub fn color_of_str(value: Option<&str>) -> Option<Hsla> {
    let value = value?.trim();
    if value.is_empty() || value.eq_ignore_ascii_case("none") {
        return None;
    }
    // gradients: use the first color
    let value = value.split(':').next().unwrap_or(value).trim();
    if let Some(hex) = value.strip_prefix('#') {
        let (r, g, b) = if hex.len() == 3 {
            (
                u8::from_str_radix(&hex[0..1].repeat(2), 16).ok()?,
                u8::from_str_radix(&hex[1..2].repeat(2), 16).ok()?,
                u8::from_str_radix(&hex[2..3].repeat(2), 16).ok()?,
            )
        } else if hex.len() >= 6 {
            (
                u8::from_str_radix(&hex[0..2], 16).ok()?,
                u8::from_str_radix(&hex[2..4], 16).ok()?,
                u8::from_str_radix(&hex[4..6], 16).ok()?,
            )
        } else {
            return None;
        };
        // `#rrggbbaa` — graphviz accepts the trailing alpha bytes
        let a = if hex.len() >= 8 {
            u8::from_str_radix(&hex[6..8], 16).unwrap_or(255)
        } else {
            255
        };
        return Some(Hsla::from(gpui_kit::rgba(
            (r as u32) << 24 | (g as u32) << 16 | (b as u32) << 8 | a as u32,
        )));
    }
    if let Some((h, s, v)) = parse_hsv(value) {
        // Graphviz's `H,S,V` scheme carries each component in 0..1 (H is a
        // fraction of the hue circle; tolerate degrees as h > 1). Convert
        // HSV → HSL for gpui's color type.
        let h = if h > 1.0 { h / 360.0 } else { h };
        let l = v * (1.0 - s / 2.0);
        let sl = if l <= 0.0 || l >= 1.0 {
            0.0
        } else {
            (v - l) / l.min(1.0 - l)
        };
        return Some(Hsla {
            h: h.rem_euclid(1.0),
            s: sl,
            l,
            a: 1.0,
        });
    }
    // the complete X11 name table graphviz ships (lib/common/color_names)
    super::x11colors::lookup(value)
}

fn parse_hsv(value: &str) -> Option<(f32, f32, f32)> {
    // Graphviz accepts both `h,s,v` and space-separated `h s v` (1.dot uses
    // spaces). `.5` without a leading zero also parses.
    let parts: Vec<&str> = value
        .split(|c: char| c == ',' || c.is_whitespace())
        .filter(|p| !p.is_empty())
        .collect();
    if parts.len() < 3 {
        return None;
    }
    let h = parts[0].trim().parse::<f32>().ok()?;
    let s = parts[1].trim().parse::<f32>().ok()?;
    let v = parts[2].trim().parse::<f32>().ok()?;
    Some((h, s, v))
}


#[cfg(test)]
mod drag_tests {
    use super::*;

    fn view_of(source: &str) -> DotView {
        let graph = std::rc::Rc::new(crate::graph::parser::parse(source).expect("parse"));
        let measured = crate::dotgen::Measured {
            node: vec![(54.0, 36.0); graph.nodes.len()],
            label: Vec::new(),
            edge_label: vec![None; graph.edges.len()],
            measure: None,
        };
        DotView::build(&crate::dotgen::layout(&graph, &measured), &graph, RankDir::TB)
    }

    /// The apex of a NORM arrowhead polygon (middle vertex of `a[1..4]`).
    fn apex(part: &ArrowPart) -> (f32, f32) {
        match part {
            ArrowPart::Polygon(pts, _) => pts[1],
            other => panic!("expected a polygon arrowhead, got {other:?}"),
        }
    }

    fn moved_by(dx: f32, dy: f32) -> Vec<(f32, f32)> {
        vec![(dx, dy), (0.0, 0.0)]
    }

    /// Offsets that move the head node `b` only.
    fn head_moved_by(dx: f32, dy: f32) -> Vec<(f32, f32)> {
        vec![(0.0, 0.0), (dx, dy)]
    }

    /// Dragging a node must carry its arrowheads along: the head arrow's apex
    /// lands on the moved node's border, and the arrowhead sits at the border
    /// (not the old spot, not the arrow base).
    #[test]
    fn arrowheads_follow_the_dragged_node() {
        let v = view_of("digraph { a -> b [dir=both] }");
        let e = &v.edges[0];
        let n = &v.nodes[1];

        // Move the head node b: the head apex follows b's new border …
        let edges = v.edges_with_offsets(&head_moved_by(100.0, 60.0)[..]);
        let moved = &edges[0];
        // build_arrow_parts emits the head arrow first, then the tail arrow.
        let head_arrow = &moved.arrows[0];
        let to = border_point(
            (n.x + 100.0, n.y + 60.0, n.w, n.h),
            far_end(e, true),
        );
        assert!((apex(head_arrow).0 - to.0).abs() < 2.0 && (apex(head_arrow).1 - to.1).abs() < 2.0,
            "head apex {:?} must sit on the moved border {:?}", apex(head_arrow), to);
        // (a hair short of the exact anchor: arrows.c's miter delta_tip pulls
        // the apex back ~penwidth/2·scale — the laid-out arrow carries the
        // same offset, so the visual tip still lands on the border.)
        // … while the unmoved tail arrow stays on dot's own anchor (again
        // modulo the miter delta_tip).
        let tail_arrow = moved.arrows.last().unwrap();
        assert!((apex(tail_arrow).0 - e.stip.0).abs() < 2.0 && (apex(tail_arrow).1 - e.stip.1).abs() < 2.0);
    }

    /// While a node is dragged, the spline must stop at the arrow's *base*
    /// (pulled back from the border by dot's `arrow_length`), so the line
    /// never runs under the arrowhead or pokes out past it.
    #[test]
    fn spline_stops_at_the_arrow_base_while_dragging() {
        let v = view_of("digraph { a -> b [dir=both] }");
        let e = &v.edges[0];
        let n = &v.nodes[1];

        let edges = v.edges_with_offsets(&head_moved_by(100.0, 60.0)[..]);
        let moved = &edges[0];
        let to = border_point((n.x + 100.0, n.y + 60.0, n.w, n.h), far_end(e, true));
        let end = moved.segments.last().unwrap()[3];
        let gap = ((to.0 - end.0).powi(2) + (to.1 - end.1).powi(2)).sqrt();
        let want = e.arrow_len(e.eflag) as f32;
        assert!(want > 0.5, "a NORM arrow pulls the spline back");
        assert!((gap - want).abs() < 1e-2, "spline must stop {want}px short of the border tip, gap {gap}");

        // And the tail side mirrors it when the tail node moves.
        let edges = v.edges_with_offsets(&moved_by(-70.0, -30.0)[..]);
        // (moved_by moves the tail node a)
        let moved = &edges[0];
        let m = &v.nodes[0];
        let from = border_point((m.x - 70.0, m.y - 30.0, m.w, m.h), far_end(e, false));
        let start = moved.segments.first().unwrap()[0];
        let gap = ((from.0 - start.0).powi(2) + (from.1 - start.1).powi(2)).sqrt();
        let want = e.arrow_len(e.sflag) as f32;
        assert!((gap - want).abs() < 1e-2, "tail spline must stop {want}px short of the border tip, gap {gap}");
    }
}

#[cfg(test)]
mod color_tests {
    use super::*;

    fn rgb(value: &str) -> [u8; 4] {
        let c = gpui_kit::Rgba::from(color_of_str(Some(value)).unwrap());
        [
            (c.r * 255.0).round() as u8,
            (c.g * 255.0).round() as u8,
            (c.b * 255.0).round() as u8,
            (c.a * 255.0).round() as u8,
        ]
    }

    #[test]
    fn hex_forms() {
        assert_eq!(rgb("#ff0000"), [255, 0, 0, 255]);
        // #rrggbbaa — the node/edge default in 1.dot
        assert_eq!(rgb("#00000088"), [0, 0, 0, 0x88]);
        assert_eq!(rgb("#0f0"), [0, 255, 0, 255]);
    }

    #[test]
    fn hsv_space_and_comma() {
        // 1.dot uses space-separated HSV with leading-dot fractions
        assert_eq!(rgb(".166 1 1"), [255, 254, 0, 255]); // hue ≈60° = yellow
        assert_eq!(rgb(".5,1,1"), [0, 255, 255, 255]); // comma form, cyan
        assert_eq!(rgb("0 1 .6"), [153, 0, 0, 255]); // red at 60% value
        assert_eq!(rgb(".083 1 1"), [255, 127, 0, 255]); // ≈30° orange
    }

    #[test]
    fn names_and_unset() {
        assert_eq!(rgb("seagreen"), [0x2e, 0x8b, 0x57, 255]);
        assert_eq!(rgb("gray40"), [102, 102, 102, 255]);
        assert_eq!(rgb("White"), [255, 255, 255, 255]);
        assert!(color_of_str(Some("none")).is_none());
        assert!(color_of_str(Some("")).is_none());
        assert!(color_of_str(None).is_none());
    }

    #[test]
    fn colorlist_takes_first() {
        assert_eq!(rgb("red:blue"), [255, 0, 0, 255]);
    }
}
