//! Headless SVG export: `dotv --svg <file.dot> [out.svg]`.
//!
//! Renders the same [`DotView`] the canvas paints — node shapes, dot's cubic
//! splines, arrowheads generated by the ported `arrows.c`, labels and cluster
//! boxes — so the geometry can be inspected (and diffed against
//! `dot -Tsvg`) without a window.

use std::fmt::Write as _;
use std::path::Path;

use crate::dotgen::{self, Measured};
use crate::graph::parser;
use crate::viz::dotview::{ArrowPart, DotView, NodeShape, ViewNode};
use crate::viz::layout::RankDir;

/// The node's label with escapes processed (`\N` etc.) and line breaks turned
/// into real newlines, for the analytic estimator.
fn label_plain(graph: &crate::graph::model::Graph, index: usize, raw: &str) -> String {
    let lines = graph.node_label_lines(index);
    if lines.is_empty() {
        return raw.to_string();
    }
    lines
        .iter()
        .map(|l| l.text.as_str())
        .collect::<Vec<_>>()
        .join("\n")
}

/// The edge's label with escapes processed.
fn label_plain_edge(graph: &crate::graph::model::Graph, index: usize, raw: &str) -> String {
    match graph.edge_label_lines(index) {
        Some(lines) if !lines.is_empty() => lines
            .iter()
            .map(|l| l.text.as_str())
            .collect::<Vec<_>>()
            .join("\n"),
        _ => raw.to_string(),
    }
}

fn font_size(attrs: &crate::graph::model::Attributes) -> f64 {
    attrs
        .get("fontsize")
        .and_then(|v| v.trim().parse::<f64>().ok())
        .filter(|v| *v > 0.0)
        .unwrap_or(14.0)
}

/// Analytic label extents (no text system here): ~0.5 em per glyph for the
/// Latin labels this harness uses, and dot's 1.2 line spacing.
fn estimate_measured(graph: &crate::graph::model::Graph) -> Measured {
    let label = graph
        .nodes
        .iter()
        .enumerate()
        .map(|(i, n)| {
            let text = label_plain(&graph, i, &n.label());
            let lines: usize = text.chars().filter(|&c| c == '\n').count() + 1;
            let f = font_size(&n.attrs);
            let w = text
                .split('\n')
                .map(|l| l.chars().count() as f64 * f * 0.5)
                .fold(0.0f64, f64::max);
            (w, lines as f64 * f * 1.2)
        })
        .collect();
    let edge_label = graph
        .edges
        .iter()
        .enumerate()
        .map(|(i, e)| {
            e.label().map(|text| {
                let text = label_plain_edge(&graph, i, text);
                let lines: usize = text.matches('\n').count() + 1;
                let f = font_size(&e.attrs);
                let w = text
                    .split('\n')
                    .map(|l| l.chars().count() as f64 * f * 0.5)
                    .fold(0.0f64, f64::max);
                (w, lines as f64 * f * 1.2)
            })
        })
        .collect();
    Measured {
        node: Vec::new(),
        label,
        edge_label,
        measure: None, // analytic record-field sizing inside the engine
    }
}

fn hex(color: gpui_kit::Hsla) -> String {
    let rgb = gpui_kit::Rgba::from(color);
    let (r, g, b) = (
        (rgb.r * 255.0).round() as u8,
        (rgb.g * 255.0).round() as u8,
        (rgb.b * 255.0).round() as u8,
    );
    // keep alpha when the color carries one (`#rrggbbaa`)
    let a = (rgb.a * 255.0).round() as u8;
    if a < 255 {
        format!("#{r:02x}{g:02x}{b:02x}{a:02x}")
    } else {
        format!("#{r:02x}{g:02x}{b:02x}")
    }
}

fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

pub fn run(path: &Path, out: Option<&Path>) {
    let source = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("dotv --svg: cannot read {}: {e}", path.display());
            std::process::exit(2);
        }
    };
    let graph = match parser::parse(&source) {
        Ok(g) => g,
        Err(e) => {
            eprintln!("dotv --svg: parse error: {e}");
            std::process::exit(3);
        }
    };
    let rank_dir = RankDir::parse(
        graph
            .graph_attrs()
            .get("rankdir")
            .map(String::as_str)
            .unwrap_or("TB"),
    );
    let measured = estimate_measured(&graph);
    let layout = dotgen::layout(&graph, &measured);
    let view = DotView::build(&layout, &graph, rank_dir);

    let (min_x, min_y, max_x, max_y) = view.bounds;
    let pad = 8.0;
    let mut svg = String::new();
    let _ = writeln!(
        svg,
        r#"<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="{vx} {vy} {vw} {vh}">"#,
        w = max_x - min_x + 2.0 * pad,
        h = max_y - min_y + 2.0 * pad,
        vx = min_x - pad,
        vy = min_y - pad,
        vw = max_x - min_x + 2.0 * pad,
        vh = max_y - min_y + 2.0 * pad,
    );
    let _ = writeln!(
        svg,
        r#"<rect x="{vx}" y="{vy}" width="{vw}" height="{vh}" fill="{bg}"/>"#,
        vx = min_x - pad,
        vy = min_y - pad,
        vw = max_x - min_x + 2.0 * pad,
        vh = max_y - min_y + 2.0 * pad,
        bg = crate::viz::dotview::color_of(graph.graph_attrs().get("bgcolor"))
            .map(hex)
            .unwrap_or_else(|| "white".to_string()),
    );

    // clusters
    for c in &view.clusters {
        let (x, y, w, h) = c.rect;
        let dash = if c.dashed {
            r#" stroke-dasharray="5,4""#
        } else {
            ""
        };
        let _ = writeln!(
            svg,
            r#"<rect x="{x:.2}" y="{y:.2}" width="{w:.2}" height="{h:.2}" rx="6" fill="none" stroke="{}"{dash}/>"#,
            hex(c.stroke)
        );
        if let Some(l) = &c.label {
            write_label_text(&mut svg, l, "#333");
        }
    }

    // edges
    for e in &view.edges {
        if e.segments.is_empty() {
            continue;
        }
        let color = hex(e.color);
        let dash = if e.dashed {
            r#" stroke-dasharray="6,4""#
        } else if e.dotted {
            r#" stroke-dasharray="1.5,3""#
        } else {
            ""
        };
        let mut d = String::new();
        for (i, seg) in e.segments.iter().enumerate() {
            if i == 0 {
                let _ = write!(d, "M {:.2},{:.2} ", seg[0].0, seg[0].1);
            }
            let _ = write!(
                d,
                "C {:.2},{:.2} {:.2},{:.2} {:.2},{:.2} ",
                seg[1].0, seg[1].1, seg[2].0, seg[2].1, seg[3].0, seg[3].1
            );
        }
        let _ = writeln!(
            svg,
            r#"<path d="{}" fill="none" stroke="{color}" stroke-width="{:.2}"{dash}/>"#,
            d.trim(),
            e.penwidth.max(1.0)
        );
        for part in &e.arrows {
            write_arrow(&mut svg, part, &color);
        }
        if let Some(l) = &e.label {
            write_label_text(&mut svg, l, "#333");
        }
    }

    // nodes
    for n in &view.nodes {
        write_node(&mut svg, n);
    }
    let _ = writeln!(svg, "</svg>");

    match out {
        Some(path) => {
            if let Err(e) = std::fs::write(path, svg) {
                eprintln!("dotv --svg: cannot write {}: {e}", path.display());
                std::process::exit(4);
            }
        }
        None => print!("{svg}"),
    }
}

fn write_node(svg: &mut String, n: &ViewNode) {
    let stroke = hex(n.stroke);
    let fill = n.fill.map(hex).unwrap_or_else(|| "none".to_string());
    let dash = if n.dotted {
        r#" stroke-dasharray="1,3""#
    } else if n.dashed {
        r#" stroke-dasharray="5,4""#
    } else {
        ""
    };
    match &n.shape {
        NodeShape::None => {}
        NodeShape::Rect(rings) => {
            // only the drawable periphery rings — the final ring, when
            // present, is the penwidth spline-clip outline
            for (i, &(x, y, w, h)) in rings.iter().enumerate().take(n.peripheries.max(1)) {
                let fill = if i == 0 { fill.as_str() } else { "none" };
                let radius = if n.rounded {
                    (6.0_f32).min(w.min(h) / 6.0)
                } else {
                    2.0
                };
                let _ = writeln!(
                    svg,
                    r#"<rect x="{x:.2}" y="{y:.2}" width="{w:.2}" height="{h:.2}" rx="{radius:.2}" fill="{fill}" stroke="{stroke}" stroke-width="{:.2}"{dash}/>"#,
                    n.penwidth
                );
            }
        }
        NodeShape::Ellipse(rings) => {
            for (i, &(rx, ry)) in rings.iter().enumerate() {
                let fill = if i == 0 { fill.as_str() } else { "none" };
                let _ = writeln!(
                    svg,
                    r#"<ellipse cx="{:.2}" cy="{:.2}" rx="{rx:.2}" ry="{ry:.2}" fill="{fill}" stroke="{stroke}"{dash}/>"#,
                    n.x + n.w / 2.0,
                    n.y + n.h / 2.0
                );
            }
        }
        NodeShape::Polygons(rings) => {
            // only the drawable periphery rings — the final ring, when
            // present, is the penwidth spline-clip outline
            for (i, ring) in rings.iter().enumerate().take(n.peripheries.max(1)) {
                let mut pts = String::new();
                for (x, y) in ring {
                    let _ = write!(pts, "{x:.2},{y:.2} ");
                }
                let fill = if i == 0 { fill.as_str() } else { "none" };
                let _ = writeln!(
                    svg,
                    r#"<polygon points="{}" fill="{fill}" stroke="{stroke}"{dash}/>"#,
                    pts.trim()
                );
            }
        }
    }
    // Records draw per-field text and the dividers between siblings; the
    // centred single label is suppressed.
    if let Some(record) = &n.record {
        for (a, b) in record.dividers.iter() {
            let _ = writeln!(
                svg,
                r#"<line x1="{:.2}" y1="{:.2}" x2="{:.2}" y2="{:.2}" stroke="{stroke}"/>"#,
                a.0, a.1, b.0, b.1
            );
        }
        if let Some(l) = &n.label {
            let color = l.color.map(hex).unwrap_or_else(|| "#000000".into());
            for (x, y, w, h, text) in record.fields.iter() {
                if text.is_empty() {
                    continue;
                }
                let _ = writeln!(
                    svg,
                    r#"<text x="{:.2}" y="{:.2}" font-size="{:.1}" text-anchor="middle" fill="{color}">{}</text>"#,
                    x + w / 2.0,
                    y + h / 2.0 + l.font_size as f32 * 0.4,
                    l.font_size,
                    escape(text)
                );
            }
        }
        return;
    }
    if let Some(l) = &n.label {
        let color = l.color.map(hex).unwrap_or_else(|| "#000000".into());
        write_label_text(svg, l, &color);
    }
}

/// Writes a label the way `emit_label` (common/labels.c:245-269) lays it out:
/// one `<text>` per line, the line's justification measured against the
/// label's whole box (`space`), the block centred on the label position.
fn write_label_text(svg: &mut String, l: &crate::viz::dotview::ViewLabel, fill: &str) {
    let lines: Vec<&str> = l.text.split('\n').collect();
    let line_height = l.font_size * 1.2;
    let total = line_height * lines.len() as f32;
    let top = l.center.1 - total / 2.0 + line_height * 0.8;
    let space = if l.space > 0.0 { l.space } else { 0.0 };
    for (i, text) in lines.iter().enumerate() {
        if text.is_empty() {
            continue;
        }
        let (anchor, x) = match l.just.get(i).copied().unwrap_or('n') {
            'l' => ("start", l.center.0 - space / 2.0),
            'r' => ("end", l.center.0 + space / 2.0),
            _ => ("middle", l.center.0),
        };
        let _ = writeln!(
            svg,
            r#"<text x="{x:.2}" y="{y:.2}" font-size="{fs:.1}" text-anchor="{anchor}" fill="{fill}">{t}</text>"#,
            y = top + line_height * i as f32,
            fs = l.font_size,
            t = escape(text)
        );
    }
}

fn write_arrow(svg: &mut String, part: &ArrowPart, color: &str) {
    match part {
        ArrowPart::Polygon(points, _filled) => {
            let mut pts = String::new();
            for (x, y) in points {
                let _ = write!(pts, "{x:.2},{y:.2} ");
            }
            let _ = writeln!(svg, r#"<polygon points="{}" fill="{color}"/>"#, pts.trim());
        }
        ArrowPart::Polyline(points) => {
            let mut d = String::new();
            for (i, (x, y)) in points.iter().enumerate() {
                let _ = write!(d, "{}{x:.2},{y:.2} ", if i == 0 { "M " } else { "L " });
            }
            let _ = writeln!(
                svg,
                r#"<path d="{}" fill="none" stroke="{color}"/>"#,
                d.trim()
            );
        }
        ArrowPart::Ellipse(a, b, _filled) => {
            let _ = writeln!(
                svg,
                r#"<ellipse cx="{:.2}" cy="{:.2}" rx="{:.2}" ry="{:.2}" fill="{color}"/>"#,
                (a.0 + b.0) / 2.0,
                (a.1 + b.1) / 2.0,
                ((b.0 - a.0) / 2.0).abs().max(0.5),
                ((b.1 - a.1) / 2.0).abs().max(0.5)
            );
        }
        ArrowPart::Bezier(b) => {
            let _ = writeln!(
                svg,
                r#"<path d="M {:.2},{:.2} C {:.2},{:.2} {:.2},{:.2} {:.2},{:.2}" fill="none" stroke="{color}"/>"#,
                b[0].0, b[0].1, b[1].0, b[1].1, b[2].0, b[2].1, b[3].0, b[3].1
            );
        }
    }
}
